### ISSUE TITLE
Redirect camera request by app

### ISSUE THREAD

**Issue by yabo-boye** [programminghoch10/CameraControl#1]
My front camera is broken, so I'd like that when an app asks for it, it gets redirected to the back camera. Is that possible? The app in question won't let me choose which camera I'd like to use, it is stuck in front camera 
Thanks

**Comment by xvan** [comment]
I've seen a cameraswap branch?

Any updates or way to find that APK?

**Comment by devnoname120** [comment]
Unfortunately the `cameraswap` branch doesn't allow to redirect both front and back to back camera. When the settings are changed they are only taken in account when the app is restarted so if the app requires to take pictures from both sides (e.g. your ID with back camera then your face with selfie camera) then you're cooked.

**Comment by devnoname120** [comment]
I vibe coded some changes on top of the `cameraswap` branch in order to make the preference changes reflect immediately in the hooks. I needed to do this because there is a banking app that requires the back camera to take a picture of your ID and then the front camera to take a selfie picture…

So with these changes I can take the first picture, swap the two cameras in the settings, and then take the second picture. Before my changes `CameraControl` would only apply preference changes when you *closed* the affected app, so in my case it would restart the verification process from the start.

Here is the branch: https://github.com/devnoname120/CameraControl/tree/cameraswap-continuous and specifically this commit: https://github.com/devnoname120/CameraControl/commit/ebcd0674a9665dd214c7e1f3f0e8e98a6853ba28?w=1

Here is a pre-compiled APK that you can install if you want to test: [cameracontrol-ebcd067.zip](https://github.com/user-attachments/files/20745467/cameracontrol-ebcd067.zip)

**Comment by bagnaram** [comment]
For some reason this above branch is causing my program to fail. My banking application is hardcoded to use the front camera by default but my device doesn't have enough megapixels on the front camera so it always fails the check. Unihertz device.

```
07-24 16:49:09.988 23191 23565 I LSPosed-Bridge: CameraManagerHook: Swapping LENS_FACING from 1 to 0
07-24 16:49:09.998 23191 23565 I LSPosed-Bridge: CameraManagerHook: Swapping LENS_FACING from 0 to 1
07-24 16:49:10.004 23191 23565 I LSPosed-Bridge: CameraManagerHook: Swapping LENS_FACING from 0 to 1
07-24 16:49:10.008 23191 23565 I LSPosed-Bridge: CameraManagerHook: Swapping LENS_FACING from 1 to 0
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: Crash unexpectedly: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at java.lang.Thread.run(Thread.java:1012)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: Caused by: java.lang.ArithmeticException: divide by zero
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at com.facetec.sdk.bb.b(SourceFile:48)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at com.facetec.sdk.bb.b(SourceFile:14)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at com.facetec.sdk.bb.i(SourceFile:1)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at com.facetec.sdk.bb.y(Unknown Source:0)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at com.facetec.sdk.z2.run(Unknown Source:0)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at com.facetec.sdk.cy.doInBackground(Unknown Source:4)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
07-24 16:49:10.085 23191 23609 I LSPosed-Bridge: 	... 3 more
```
